CREATE TABLE "incentive_records" (
	"incentive_id" text PRIMARY KEY NOT NULL,
	"recipient_user_id" text NOT NULL,
	"recipient_user_name" text NOT NULL,
	"clinic_id" text NOT NULL,
	"type" text NOT NULL,
	"amount" numeric(10, 2) NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"date_string" text NOT NULL,
	"description" text,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payroll_entries" (
	"entry_id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"user_name" text NOT NULL,
	"user_role" text NOT NULL,
	"clinic_id" text NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"date_string" text NOT NULL,
	"is_sunday" boolean DEFAULT false NOT NULL,
	"total_day_earning" numeric(10, 2) DEFAULT '0',
	"gd_hours_worked" numeric(5, 2),
	"gd_daily_revenue" numeric(12, 2),
	"gd_daily_earning" numeric(10, 2),
	"gd_daily_target_achieved" boolean DEFAULT false,
	"gd_multiplier" numeric(2, 1) DEFAULT '1',
	"gd_referral_incentive" numeric(10, 2) DEFAULT '0',
	"gd_referral_count" numeric(4, 0) DEFAULT '0',
	"ad_hours_worked" numeric(5, 2),
	"ad_daily_earning" numeric(10, 2),
	"ad_is_deducted" boolean DEFAULT false,
	"ad_sunday_incentives" numeric(10, 2) DEFAULT '0',
	"ad_sunday_tasks_count" numeric(4, 0) DEFAULT '0',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monthly_payroll" (
	"payroll_id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"user_name" text NOT NULL,
	"user_role" text NOT NULL,
	"clinic_id" text NOT NULL,
	"month" numeric(2, 0) NOT NULL,
	"year" numeric(4, 0) NOT NULL,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"generated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"generated_by" text NOT NULL,
	"gd_accumulated_salary" numeric(12, 2) DEFAULT '0',
	"gd_sunday_earning" numeric(12, 2) DEFAULT '0',
	"gd_referral_incentives_total" numeric(12, 2) DEFAULT '0',
	"gd_total_monthly_revenue" numeric(14, 2) DEFAULT '0',
	"gd_monthly_target_achieved" boolean DEFAULT false,
	"gd_monthly_target_bonus" numeric(12, 2) DEFAULT '0',
	"gd_total_final_salary" numeric(12, 2) DEFAULT '0',
	"gd_total_days_worked" numeric(4, 0) DEFAULT '0',
	"gd_target_days_count" numeric(4, 0) DEFAULT '0',
	"ad_regular_earning" numeric(12, 2) DEFAULT '0',
	"ad_sunday_earning" numeric(12, 2) DEFAULT '0',
	"ad_weekly_bonuses_total" numeric(12, 2) DEFAULT '0',
	"ad_sunday_task_incentives_total" numeric(12, 2) DEFAULT '0',
	"ad_total_final_salary" numeric(12, 2) DEFAULT '0',
	"ad_total_days_worked" numeric(4, 0) DEFAULT '0'
);
