export const defaultAppointmentCategories = [
  { name: 'CONSULTATION', color: '#3B82F6' },
  { name: 'EXTRACTION', color: '#EF4444' },
  { name: 'FILLING', color: '#F59E0B' },
  { name: 'SCALING', color: '#10B981' },
  { name: 'RCT', color: '#06B6D4' },
  { name: 'RCT RETREATMENT', color: '#0EA5E9' },
  { name: 'WISDOM TOOTH EXTRACTION', color: '#9F1239' },
  { name: 'ORTHO', color: '#8B5CF6' },
  { name: 'IMPLANT', color: '#6366F1' },
  { name: 'SURGICAL', color: '#DC2626' },
  { name: 'BLEACHING', color: '#F59E0B' },
  { name: 'GIC FILLING', color: '#14B8A6' },
  { name: 'COMPOSITE FILLING', color: '#22D3EE' },
  { name: 'I-SEAL FILLING', color: '#06B6D4' },
  { name: 'FA - METAL', color: '#78716C' },
  { name: 'FA - TOOTH COLOUR', color: '#FDE68A' },
  { name: 'FA - CLEAR ALIGN', color: '#A78BFA' },
  { name: 'FA - INVISALIGN', color: '#8B5CF6' },
  { name: 'RPD UPPER', color: '#D97706' },
  { name: 'NO CATEGORY', color: '#6B7280' },
];