export const defaultLabStageTemplates: Array<{ name: string; description: string }> = [
  { name: 'Teeth ceramic cap', description: 'Fabrication of ceramic cap for teeth' },
  { name: 'Crown preparation', description: 'Tooth preparation for crown' },
  { name: 'Implant placement', description: 'Surgical placement of implant' },
  { name: 'Try-in', description: 'Trial fitting of prosthesis' },
  { name: 'Final cementation', description: 'Permanent cementation' },
  { name: 'Wax-up', description: 'Wax pattern fabrication' },
  { name: 'Metal framework', description: 'Metal coping / framework' },
  { name: 'Opaque layer', description: 'Application of opaque layer' },
  { name: 'Porcelain build-up', description: 'Layering of porcelain' },
  { name: 'Final glaze', description: 'Glazing and finishing' },
  { name: 'Polishing', description: 'Final polishing' },
  { name: 'Shade matching', description: 'Matching shade with adjacent teeth' },
  { name: 'Bite registration', description: 'Recording occlusion' },
  { name: 'Impression taking', description: 'Primary / secondary impression' },
  { name: 'Model preparation', description: 'Pouring and preparing model' },
  { name: 'Die preparation', description: 'Die cutting and ditching' },
  { name: 'Articulation', description: 'Mounting on articulator' },
  { name: 'Coping trial', description: 'Metal coping trial' },
  { name: 'Bisque trial', description: 'Porcelain bisque trial' },
  { name: 'Occlusal adjustment', description: 'Adjusting occlusion' },
  { name: 'Veneer preparation', description: 'Veneer tooth preparation' },
  { name: 'Veneer bonding', description: 'Bonding of veneer' },
  { name: 'Denture try-in', description: 'Try-in of denture' },
  { name: 'Denture finishing', description: 'Final finishing of denture' },
  { name: 'Implant impression', description: 'Open / closed tray impression' },
  { name: 'Abutment selection', description: 'Selection of abutment' },
  { name: 'Framework try-in', description: 'Framework try-in' },
  { name: 'Staining & glazing', description: 'Custom staining and glazing' },
];
