export const defaultLabShades = [
  { name: 'A1', hexColor: '#F8E9C8' },
  { name: 'A2', hexColor: '#F5E2B8' },
  { name: 'A3', hexColor: '#F0D9A8' },
  { name: 'A3.5', hexColor: '#E8C99A' },
  { name: 'A4', hexColor: '#DDB98C' },
  { name: 'B1', hexColor: '#FFF6CC' },
  { name: 'B2', hexColor: '#FFF0B8' },
  { name: 'B3', hexColor: '#F5E6A8' },
  { name: 'B4', hexColor: '#E8D99A' },
  { name: 'C1', hexColor: '#EDE8D8' },
  { name: 'C2', hexColor: '#E5DDC8' },
  { name: 'C3', hexColor: '#D8CCB0' },
  { name: 'C4', hexColor: '#C9B99A' },
  { name: 'D2', hexColor: '#F0E0D0' },
  { name: 'D3', hexColor: '#E8D0B8' },
  { name: 'D4', hexColor: '#D8C0A8' },
  { name: 'Bleach', hexColor: '#FFFEF8' },
  { name: 'BL1', hexColor: '#FFFEF0' },
  { name: 'BL2', hexColor: '#FFF8E0' },
  { name: 'BL3', hexColor: '#FFF0D0' },
  { name: 'BL4', hexColor: '#FFE8C0' },
];
