export const defaultLabWorkTypes = [
  'Ceramic Crown',
  'Zirconia Crown',
  'Metal Crown',
  'PFM Crown',
  'Veneers',
  'Laminates',
  'Implant Crown',
  'Implant Abutment',
  'Denture - Complete',
  'Denture - Partial',
  'Bridge - 3 Unit',
  'Bridge - 4 Unit',
  'Inlay',
  'Onlay',
  'Orthodontic Appliance',
  'Night Guard',
  'Whitening Trays',
  'Maryland Bridge',
  'Post & Core',
  'Wax-up',
];
