export const defaultMedicalConditions = [
  'Hypertension',
  'Diabetes',
  'Asthma',
  'Epilepsy',
  'Heart Disease',
  'Allergies',
  'Gastric Ulcers',
  'Undergone Dental Treatment Earlier',
  'Bleeding Disorders',
  'Undergone cardiac stunt',
  'Anemia',
  'Psychiatric Problems',
  'HEARING IMPAIRED',
  'VERTICO',
  'H/O PARALYSIS',
  'Hyperthyroid',
  'HYPOTENSION',
  'NO MEDICAL HISTORY',
  'FAMILY HISTORY OF DIABETES',
  'HYPOTHYROID',
  'CHRONIC MYLOID LEUKIMIA',
  'PREGNANT',
  'MOTHER FEEDING',
  'Thyroid',
  'CARDIAC VALVULAR PROBLEM',
  'Hypercholesterolemia',
  'CABG',
  'DIALYSIS',
  'Rheumatoid arthritis',
  'HYPERCHOLESTREMIA',
  'LUNG INFECTION',
  'ALLERGIC TO PENCILLIN',
  'BLOOD PRESSURE',
  'KIDNEY PROBLEM',
  'Hypertension under medication',
  'ALLERGIC TO SARIDON TAB',
  'ALLERGIC TO VOVERAN inj.(DICLOFENAC)',
  'ALLERGIC TO TAB ANALGIN',
  'ALLERGIC TO OFLOXACIN',
  'norfloxacin & ciprofloxacin allergy',
  'WHEEZING',
  'Allergic to IBUPROFEN',
  'Allergic to DICYCLOMINE HYDROCHLORIDE',
  'SKIN PROBLEM',
  'Kidney Stone',
  'Vertigo',
  'Stroke',
  'Hyper Lipidemea',
  'CANCER',
  'Breastfeeding',
  'KIDNEY DISEASE',
  'High creatinine level',
  'Vitiligo',
  'Neuro',
  'NEUROLOGY',
  'ANXIETY',
  'CEF ALLERGY',
  'SPORIDEX ALLERGY',
  'ORTHO CASE MOTIVATED BY DR MUBEEN',
];