export const defaultPatientGroups = [
  'WISDOM TOOTH EXTRACTION',
  'ADAYAR',
  'RCT',
  'EXTRACTION',
  'KODAMBAKKAM',
  'FA',
  'RCT 46',
  'MYLAPORE CLINIC',
  'I-SEAL FILING',
  'FA- METAL',
  'RCT RETREATMENT',
  'RCT 26',
  'Dr.EZHILMARAN',
  'Outside consultation',
  'child 1-4',
  'DR.PRASANNA',
  'LKS',
  'RCT 16',
  'RCT 17',
  'RCT 33',
  'RCT 36',
  'RCT 42',
  'GIC TYPE 9 EXTRA FILLING',
  'FILLING-GIC',
  'FA- METAL SELF LIGATING',
  'RPD UPPER',
  'IMPLANT',
  'Mylapore',
  'E1 POLISE STATION MYLAPORE',
  'RCT 11',
  'RCT 12',
  'RCT 13',
  'RCT 14',
  'RCT 15',
  'RCT 18',
  'RCT 21',
  'RCT 22',
  'RCT 23',
  'RCT 24',
  'RCT 25',
  'RCT 27',
  'RCT 28',
  'RCT 31',
  'RCT 32',
  'RCT 34',
  'RCT 35',
  'RCT 37',
  'RCT 38',
  'RCT 41',
  'RCT 43',
  'RCT 44',
  'RCT 45',
  'RCT 47',
  'RCT 48',
  'FILLING-GIC TYPE 9 EXTRA',
  'FILLING-I SEAL',
  'FILLING-COMPOSITE',
  'FILLING-GIC LC',
  'FILLING-TF',
  'FA- TOOTH COLOUR',
  'FA- TOOTH COLOUR SELF LIGATING',
  'FA- LINGUAL',
  'FA- CLEAR ALIGN',
  'FA- INVIZHIALIGN',
  'FA- INVISALIGN',
  'KODAMBAKKAM CLINIC',
];