export interface SeedProcedure {
  name: string;
  defaultCost: number;
}

// Full dental procedure catalog parsed from clinic price list.
// Costs are default/suggested prices in INR and editable per patient.
export const proceduresData: SeedProcedure[] = [
  { name: "ABRASION", defaultCost: 0 },
  { name: "ABSORBABLE SUTURE", defaultCost: 600 },
  { name: "ABUTMENT -ADIN", defaultCost: 3000 },
  { name: "ABUTMENT ADIN", defaultCost: 2500 },
  { name: "ABUTMENT SCREW CHANGED", defaultCost: 5000 },
  { name: "ACRYLIC CROWN", defaultCost: 2000 },
  { name: "AGE CERTIFICATE", defaultCost: 0 },
  { name: "AIRFLOW SCALING", defaultCost: 3000 },
  { name: "ALIGNER", defaultCost: 0 },
  { name: "ALVEOPLASTY", defaultCost: 1000 },
  { name: "AMFLOR MOUTHWASH", defaultCost: 200 },
  { name: "Anterior Spilinting", defaultCost: 3500 },
  { name: "ANTERIOR BITE PLAN", defaultCost: 5000 },
  { name: "ANTERIOR CROSSBITE C...", defaultCost: 0 },
  { name: "ANTERIOR TOOTH REPLA...", defaultCost: 60000 },
  { name: "ANTERIOR TOOTH REPLA...", defaultCost: 65000 },
  { name: "ARCH BAR FIXATION", defaultCost: 50000 },
  { name: "ARCH WIRE", defaultCost: 0 },
  { name: "ball head implant an...", defaultCost: 15000 },
  { name: "BAND REFIXATION", defaultCost: 300 },
  { name: "BASAL IMPLANT", defaultCost: 20000 },
  { name: "Bgb bvvvvvvvvvvvvvvv...", defaultCost: 0 },
  { name: "BI CORTICAL IMPLANT", defaultCost: 20000 },
  { name: "BIO -OSS(COLLOGEN)", defaultCost: 5000 },
  { name: "BIO OSS", defaultCost: 9700 },
  { name: "BIOPSY", defaultCost: 2000 },
  { name: "BLANCONE BLEACH", defaultCost: 15000 },
  { name: "BLANCONE POWER TOOTH...", defaultCost: 15000 },
  { name: "BLEACHING BOOST", defaultCost: 8000 },
  { name: "BLEACHING SYRINGE (GEL)", defaultCost: 2000 },
  { name: "BLEACHING TRAY", defaultCost: 2000 },
  { name: "blood sugar test", defaultCost: 300 },
  { name: "BONE GRAFT", defaultCost: 0 },
  { name: "BONE GRAFT PLACED & ...", defaultCost: 30000 },
  { name: "BONE SUBSTITUE - GEI...", defaultCost: 15000 },
  { name: "Bone substitute material", defaultCost: 1200 },
  { name: "BONE TRIMMING", defaultCost: 1000 },
  { name: "BONY SPICULES", defaultCost: 500 },
  { name: "BRACKET RE FIXATION", defaultCost: 500 },
  { name: "BRACKET REMOVAL", defaultCost: 1500 },
  { name: "CAP FIXATION", defaultCost: 0 },
  { name: "CAP REFIXATION", defaultCost: 1000 },
  { name: "CAP SPLINT WITH ANTE...", defaultCost: 3000 },
  { name: "CAP SPLINT WITH TOOT...", defaultCost: 1500 },
  { name: "caps splint", defaultCost: 1500 },
  { name: "Cast Partial Denture", defaultCost: 0 },
  { name: "CAVITY FILLING", defaultCost: 1000 },
  { name: "CBCT", defaultCost: 1000 },
  { name: "CBCT AND OPG", defaultCost: 1500 },
  { name: "CERAIMC CROWN WITH INLAY", defaultCost: 4500 },
  { name: "CERAMIC CROWN REPAIR", defaultCost: 1000 },
  { name: "CERAMIC CROWN ( CAP ) -P", defaultCost: 3500 },
  { name: "CERAMIC CROWN (CAD-CAM)", defaultCost: 4000 },
  { name: "CERAMIC CROWN REPEAT...", defaultCost: 1000 },
  { name: "CERAMIC FACING CROWN", defaultCost: 0 },
  { name: "CERMAIC CROWN (CAP)-...", defaultCost: 0 },
  { name: "CERMAIC CROWN (CAP)-P", defaultCost: 4000 },
  { name: "CERVICAL ABRASION FI...", defaultCost: 500 },
  { name: "CHEERIO", defaultCost: 70 },
  { name: "CHEQUE RETURN BANK F...", defaultCost: 200 },
  { name: "CHIN CAP", defaultCost: 2000 },
  { name: "CHIN CUP APPLIANCE", defaultCost: 5000 },
  { name: "CLEAR ALIGNER", defaultCost: 0 },
  { name: "CLOHEX PLUS MOUTHWASH", defaultCost: 90 },
  { name: "COLGATE PASTE", defaultCost: 100 },
  { name: "COLLAGEN PLUG", defaultCost: 1000 },
  { name: "complete denture", defaultCost: 25000 },
  { name: "COMPLETE DENTURE REPAIR", defaultCost: 1000 },
  { name: "COMPLETE DENTURE UPPER", defaultCost: 10000 },
  { name: "COMPLETE DENTURE- LOWER", defaultCost: 10000 },
  { name: "COMPOSITE BITE FOR P...", defaultCost: 500 },
  { name: "COMPOSITE FILLING ( ...", defaultCost: 400 },
  { name: "COMPOSITE-MID LINE D...", defaultCost: 500 },
  { name: "Consultation", defaultCost: 300 },
  { name: "CORE BUILD-UP", defaultCost: 0 },
  { name: "CORE FILLING", defaultCost: 1500 },
  { name: "CORE FILLING - METAL", defaultCost: 1500 },
  { name: "CORONOPLASTY", defaultCost: 5000 },
  { name: "crowm material", defaultCost: 1500 },
  { name: "CROWN", defaultCost: 2000 },
  { name: "CROWN - ACRALIC", defaultCost: 2000 },
  { name: "CROWN AND BRIDGE", defaultCost: 4000 },
  { name: "CROWN AND BRIDGE REF...", defaultCost: 700 },
  { name: "CROWN LENGTHENING", defaultCost: 0 },
  { name: "CROWN REFIXATION", defaultCost: 500 },
  { name: "CROWN REMOVAL", defaultCost: 500 },
  { name: "CROWN- ZIRCONIUM", defaultCost: 7000 },
  { name: "CUSTOMIZE ABUTMENT", defaultCost: 0 },
  { name: "CYST ENUCLEATION", defaultCost: 4000 },
  { name: "CYST ENUCLEATION AND...", defaultCost: 10000 },
  { name: "DAMON MALOCCLUSION C...", defaultCost: 60000 },
  { name: "DEBONDING", defaultCost: 2000 },
  { name: "Dental Implant", defaultCost: 15000 },
  { name: "DENTAL IMPLANT WITH ...", defaultCost: 20000 },
  { name: "DENTAL STONE MODEL", defaultCost: 500 },
  { name: "DENTCARE ZIRCONIA SU...", defaultCost: 10000 },
  { name: "DENTO ALVELOLAR # LOWER", defaultCost: 0 },
  { name: "DENTOALVEOLAR FRACTU...", defaultCost: 30000 },
  { name: "DENTURE REPAIR - UPPER", defaultCost: 2000 },
  { name: "DENTURE ADHESIVE", defaultCost: 315 },
  { name: "DENTURE BASE", defaultCost: 1000 },
  { name: "DENTURE HARD LINER", defaultCost: 2000 },
  { name: "DENTURE REPAIR", defaultCost: 500 },
  { name: "DENTURE TRIMMING", defaultCost: 500 },
  { name: "DENTURE UPPER AND LO...", defaultCost: 20000 },
  { name: "DIGITAL INTRA ORAL SCAN", defaultCost: 2000 },
  { name: "DIGITAL OPG ( 2D PAN i )", defaultCost: 500 },
  { name: "DMLS METAL CROWN", defaultCost: 2500 },
  { name: "DMLS- CERAMIC CROWN ...", defaultCost: 5000 },
  { name: "DRY SOCKET- ZnOE PACK", defaultCost: 300 },
  { name: "DUAL RESTORATION", defaultCost: 1000 },
  { name: "DUESTOM", defaultCost: 118 },
  { name: "EASY ORTHO", defaultCost: 2000 },
  { name: "ENAMELOPLASTY", defaultCost: 200 },
  { name: "ENDOCROWN", defaultCost: 10000 },
  { name: "ENTRANCE FILLING (CO...", defaultCost: 1000 },
  { name: "ENTRANCE FILLING - A...", defaultCost: 1000 },
  { name: "EXCISION", defaultCost: 2500 },
  { name: "Extraction", defaultCost: 1000 },
  { name: "EXTRACTION - REMNANT...", defaultCost: 1000 },
  { name: "EXTRACTION -TOOTH PART", defaultCost: 500 },
  { name: "EXTRACTION FOLLOWED ...", defaultCost: 3000 },
  { name: "EXTRACTION FOLLOWED ...", defaultCost: 2000 },
  { name: "EXTRACTION FRACTURED...", defaultCost: 1000 },
  { name: "EXTRACTION WITH SUTURE", defaultCost: 1000 },
  { name: "EXTRACTION- PARA-MOLAR", defaultCost: 1000 },
  { name: "F A", defaultCost: 4000 },
  { name: "FA CHECKUP", defaultCost: 300 },
  { name: "FA ORTHO CHECK UP", defaultCost: 300 },
  { name: "FA-LINGUAL", defaultCost: 45000 },
  { name: "FA-METAL", defaultCost: 20000 },
  { name: "FA-SELF LIGATING -TO...", defaultCost: 0 },
  { name: "FA-SELF LIGATING METAL", defaultCost: 35000 },
  { name: "FA-SELF LIGATING SMA...", defaultCost: 65000 },
  { name: "FA-TOOTH COLOUR", defaultCost: 20000 },
  { name: "FILLING - CIMPOSITE ...", defaultCost: 1000 },
  { name: "FILLING - GIC FILLING", defaultCost: 600 },
  { name: "FILLING - IONOFIL MOLAR", defaultCost: 1000 },
  { name: "FILLING - TYPE 7 GC...", defaultCost: 1000 },
  { name: "FILLING - TYPE 7 ( W...", defaultCost: 1000 },
  { name: "Filling or root cana...", defaultCost: 4000 },
  { name: "FILLING- CAPSULE EQU...", defaultCost: 1000 },
  { name: "FILLING- CERVICAL C...", defaultCost: 500 },
  { name: "FILLING- COMPOSITE RESIN", defaultCost: 800 },
  { name: "FILLING- COMPOSITE R...", defaultCost: 1000 },
  { name: "FILLING- GIC TYPE 9 ...", defaultCost: 900 },
  { name: "FILLING- IONOFIL- MOLAR", defaultCost: 800 },
  { name: "FILLING- TYPE 7 (PINK )", defaultCost: 1000 },
  { name: "FILLING- ZNOE", defaultCost: 300 },
  { name: "FILLING-GIC TYPE 9 EXTRA", defaultCost: 800 },
  { name: "FILLING-GIC TYPE 9 E...", defaultCost: 1000 },
  { name: "FILLING-HY BOND RESI...", defaultCost: 1000 },
  { name: "FILLINGS", defaultCost: 1000 },
  { name: "FIXED & REMOVABLE RE...", defaultCost: 5000 },
  { name: "FIXED APPILANCE - METAL", defaultCost: 27000 },
  { name: "fixed retainer", defaultCost: 3500 },
  { name: "FIXED TOUNGE GRIP AP...", defaultCost: 3500 },
  { name: "FLAP INCISION", defaultCost: 200 },
  { name: "Flap surgery", defaultCost: 10000 },
  { name: "Flap Surgery with Graft", defaultCost: 0 },
  { name: "FLOSAL", defaultCost: 32100 },
  { name: "FLOURIDE VARNISH", defaultCost: 500 },
  { name: "FLUORIDE VARNISH", defaultCost: 1000 },
  { name: "Fluroide Application", defaultCost: 0 },
  { name: "FPD", defaultCost: 500 },
  { name: "FPD ACRALIC", defaultCost: 1500 },
  { name: "FPD ACRLIC FACING- METAL", defaultCost: 2000 },
  { name: "FPD CERAMIC REFIXATION", defaultCost: 1000 },
  { name: "FPD CERAMIC-P", defaultCost: 3500 },
  { name: "FPD METAL", defaultCost: 0 },
  { name: "FPD REFIXATION", defaultCost: 600 },
  { name: "FPD REMOVAL", defaultCost: 500 },
  { name: "FPD ZIRCONIUM CERAMIC", defaultCost: 7000 },
  { name: "FRENECTOMY", defaultCost: 2000 },
  { name: "FULL MOUTH ENAMELOP...", defaultCost: 1000 },
  { name: "FULL MOUTH ORAL PROP...", defaultCost: 2000 },
  { name: "FULL MOUTH REHABILIT...", defaultCost: 0 },
  { name: "G - CAM CROWN", defaultCost: 6000 },
  { name: "G-CAM CROWN", defaultCost: 8000 },
  { name: "G-CAM INLAY", defaultCost: 0 },
  { name: "GAP FILLING", defaultCost: 200 },
  { name: "GEL METROHEX", defaultCost: 30 },
  { name: "GIC ( TYPE VII GLASS...", defaultCost: 1000 },
  { name: "GIC FILLING - TYPE 7...", defaultCost: 1000 },
  { name: "gingival curettage", defaultCost: 4800 },
  { name: "GINGIVECTOMY", defaultCost: 0 },
  { name: "GINGIVOPLASTY", defaultCost: 0 },
  { name: "HABIT BREAKING APPLIANCE", defaultCost: 0 },
  { name: "Hard Splint 1mm", defaultCost: 1500 },
  { name: "HARD SPLINT RETAINER", defaultCost: 2000 },
  { name: "HAWLEYS", defaultCost: 4000 },
  { name: "HAWLEYS WITH ANTERIO...", defaultCost: 5000 },
  { name: "HEALING CAP", defaultCost: 2000 },
  { name: "HYBRID SMART MOUTH GUARD", defaultCost: 5000 },
  { name: "HYBRID TEETH", defaultCost: 0 },
  { name: "HYDENT PRO", defaultCost: 150 },
  { name: "HYDENT-K PASTE", defaultCost: 80 },
  { name: "I BAR WITH INTERIM TEETH", defaultCost: 20000 },
  { name: "IMPACTION FOLLOWED B...", defaultCost: 10000 },
  { name: "IMPALNMT CROWN - CER...", defaultCost: 5000 },
  { name: "IMPLANT - ADIN", defaultCost: 15000 },
  { name: "IMPLANT - HYBRID TEE...", defaultCost: 10000 },
  { name: "IMPLANT ABUTMENT", defaultCost: 5000 },
  { name: "IMPLANT CROWN", defaultCost: 6000 },
  { name: "IMPLANT CROWN - ZIRC...", defaultCost: 8000 },
  { name: "IMPLANT CROWN WITH A...", defaultCost: 5000 },
  { name: "IMPLANT EXPLANTATION", defaultCost: 0 },
  { name: "IMPLANT OVER DENTURE...", defaultCost: 1500 },
  { name: "IMPLANT REMOVAL", defaultCost: 5000 },
  { name: "IMPLANT TEMP CROWN", defaultCost: 2000 },
  { name: "IMPLANT TEMPORARY TO...", defaultCost: 2000 },
  { name: "IMPLANT WITH ATTCHME...", defaultCost: 25000 },
  { name: "IMPLANT WITH TOOTH R...", defaultCost: 0 },
  { name: "IMPLANT- INTERIM TEETH", defaultCost: 5000 },
  { name: "IMPLANT- METAL BAR", defaultCost: 15000 },
  { name: "IMPLANT- METAL BAR W...", defaultCost: 30000 },
  { name: "IMPLANT-SCREW RETAIN...", defaultCost: 1500 },
  { name: "incision and drainge", defaultCost: 100 },
  { name: "inlay", defaultCost: 1000 },
  { name: "INLAY REFIXING", defaultCost: 1000 },
  { name: "INLAY-METAL", defaultCost: 2000 },
  { name: "INTERDENTAL BRUSH", defaultCost: 180 },
  { name: "INTERIM CROWN AND BRIDGE", defaultCost: 2000 },
  { name: "INTERIM DENTURE", defaultCost: 20000 },
  { name: "INTERIM TEETH", defaultCost: 2000 },
  { name: "INVISALIGN", defaultCost: 0 },
  { name: "INVISALIGN GO", defaultCost: 120000 },
  { name: "IOPA", defaultCost: 300 },
  { name: "IOPA - RVG XRAY", defaultCost: 300 },
  { name: "JC -CERAMIC", defaultCost: 2000 },
  { name: "JC VITALIUM", defaultCost: 900 },
  { name: "KIDODENT XP", defaultCost: 180 },
  { name: "Laminates & Veneers", defaultCost: 7000 },
  { name: "LASER CROWN LENGTHENING", defaultCost: 3000 },
  { name: "LASER DE PIGMENTATION", defaultCost: 5000 },
  { name: "Laser disinfection", defaultCost: 7000 },
  { name: "LASER EXCISION", defaultCost: 5000 },
  { name: "LASER FRENECTOMY", defaultCost: 5000 },
  { name: "LASER OPERCULECTOMY", defaultCost: 2000 },
  { name: "LASER POCKET DISINFE...", defaultCost: 10000 },
  { name: "LC COMPOSITE (IPS EM...", defaultCost: 2000 },
  { name: "LC COMPOSITE (IVOCLA...", defaultCost: 0 },
  { name: "LIGHT CURE COMPOSITE...", defaultCost: 1000 },
  { name: "LINGUAL FRENECTOMY", defaultCost: 4500 },
  { name: "LIP BUMPER", defaultCost: 2000 },
  { name: "LOWER FIXED FULL ARC...", defaultCost: 160000 },
  { name: "LOWER FULL ARCH REHA...", defaultCost: 150000 },
  { name: "LOWER HAWLEYS", defaultCost: 2500 },
  { name: "MALO BRIDGE", defaultCost: 0 },
  { name: "MALOCCLUSION CORRECTION", defaultCost: 45000 },
  { name: "MALOCCLUSION CORRECT...", defaultCost: 50000 },
  { name: "MARSUPIALIZATION", defaultCost: 0 },
  { name: "MARYLAND BRIDGE - ZI...", defaultCost: 0 },
  { name: "MARYLAND BRIDGE- CERAMIC", defaultCost: 0 },
  { name: "MEASUREMENT-ALGINATE...", defaultCost: 1000 },
  { name: "medicines", defaultCost: 0 },
  { name: "METAL ABUTMENR", defaultCost: 3000 },
  { name: "METAL COPPING", defaultCost: 1500 },
  { name: "METAL CROWN", defaultCost: 2000 },
  { name: "METAL CROWN REFIXATION", defaultCost: 500 },
  { name: "METAL POST", defaultCost: 1500 },
  { name: "MID-LINE DIASTEMA CL...", defaultCost: 3500 },
  { name: "MILK TEETH EXTRACTION", defaultCost: 700 },
  { name: "MINOR SURGICAL PROCE...", defaultCost: 48000 },
  { name: "MOLAR BAND LUTING", defaultCost: 0 },
  { name: "MTA PLACEMENT", defaultCost: 1500 },
  { name: "MUCOCELE SURIGICAL E...", defaultCost: 4500 },
  { name: "MULTIUNIT ABUTMENT", defaultCost: 0 },
  { name: "MYOFUNCTIONAL APPLIANCE", defaultCost: 5000 },
  { name: "MYOFUNCTIONAL APPLIA...", defaultCost: 5000 },
  { name: "NOBEL BIOCARE DENTAL...", defaultCost: 35000 },
  { name: "NOBEL BIOCARE IMPLANT", defaultCost: 35000 },
  { name: "NON OSSEOINTEGRATED ...", defaultCost: 3000 },
  { name: "NOVABONE (Bioactive ...", defaultCost: 8000 },
  { name: "NOVABONE PUTTY", defaultCost: 8000 },
  { name: "nvisalign® Clear Ali...", defaultCost: 150000 },
  { name: "OCCLUSAL REDUCTION I...", defaultCost: 500 },
  { name: "oden", defaultCost: 750 },
  { name: "OLD CROWN SCREW ACCE...", defaultCost: 1500 },
  { name: "OPERCULECTOMY", defaultCost: 1000 },
  { name: "OPERTCULECTOMY", defaultCost: 1000 },
  { name: "OPG AND CONSULTATION", defaultCost: 500 },
  { name: "ORAHEX PLUS MOUTHWASH", defaultCost: 60 },
  { name: "ORAL -B SESITIVE SUP...", defaultCost: 50 },
  { name: "ORAL -B TOOTH BRUSH", defaultCost: 50 },
  { name: "ORAL PROPHYLAXIS", defaultCost: 2000 },
  { name: "ORAL SCREEN", defaultCost: 2500 },
  { name: "ORAL-B TOOTH BRUSH F...", defaultCost: 40 },
  { name: "ortho continous trea...", defaultCost: 6000 },
  { name: "ORTHO IMPRESSION", defaultCost: 1000 },
  { name: "ORTHO- BRUSH", defaultCost: 100 },
  { name: "ORTHODONTIC BRUSH", defaultCost: 50 },
  { name: "ORTHOPANTOMOGRAM", defaultCost: 500 },
  { name: "PERI APICAL SURGERY", defaultCost: 3000 },
  { name: "PERI CORONAL FLAP EX...", defaultCost: 1000 },
  { name: "pit and fissure sealant", defaultCost: 500 },
  { name: "plate removal", defaultCost: 8000 },
  { name: "PMMA CROWN", defaultCost: 2000 },
  { name: "PMMA CROWN AND BRIDGE", defaultCost: 2000 },
  { name: "Polident", defaultCost: 300 },
  { name: "PORCELAIN JACKET", defaultCost: 5000 },
  { name: "PORCELINE LAMINATE", defaultCost: 15000 },
  { name: "POST", defaultCost: 0 },
  { name: "POST &CORE", defaultCost: 2000 },
  { name: "POST REFIXATION", defaultCost: 1000 },
  { name: "POST-FIBRE", defaultCost: 2000 },
  { name: "POSTERIOR BITE PLANE", defaultCost: 50000 },
  { name: "PREMIUM- upper and l...", defaultCost: 6000 },
  { name: "Provisional fixed pa...", defaultCost: 25000 },
  { name: "PTERYGOID IMPLANT", defaultCost: 25000 },
  { name: "PULP CAPPING + IONOS...", defaultCost: 1000 },
  { name: "PULP THERAPY", defaultCost: 0 },
  { name: "PULP THERAPY WITH ST...", defaultCost: 5000 },
  { name: "PULPECTOMY", defaultCost: 3000 },
  { name: "PULPECTOMY + COMPOSI...", defaultCost: 3500 },
  { name: "PULPECTOMY WITH STAI...", defaultCost: 5000 },
  { name: "PULPOTOMY WITH STAIN...", defaultCost: 0 },
  { name: "PULPTOMY", defaultCost: 1500 },
  { name: "RCT-CLOSED DRESSING", defaultCost: 0 },
  { name: "RCT-OBTURATION", defaultCost: 0 },
  { name: "RE ROOT CANAL TREAMENT", defaultCost: 4500 },
  { name: "RE TREATMENT - RCT W...", defaultCost: 4500 },
  { name: "RE- ROOT CANAL TREATMENT WITH BIO CERAMIC SEALER - CERASEAL", defaultCost: 4500 },
  { name: "REFIXATION-ZIRCONIUM CROWN/FPD", defaultCost: 500 },
  { name: "removable anterior biteplan", defaultCost: 5000 },
  { name: "REMOVABLE DENTURE BASE", defaultCost: 1000 },
  { name: "REMOVABLE PARTIAL DENTURE 5", defaultCost: 5000 },
  { name: "removable retainer", defaultCost: 2500 },
  { name: "REMOVABLE TOOTH REPLACEMENT", defaultCost: 1000 },
  { name: "REMOVABLE TOOTH REPLACEMENT UPPER & LOWER", defaultCost: 0 },
  { name: "Removal Full Mouth Complete Denture", defaultCost: 20000 },
  { name: "Removal Partial Dentures", defaultCost: 500 },
  { name: "RETAINER CORRECTION", defaultCost: 500 },
  { name: "retainer removal", defaultCost: 800 },
  { name: "REXIDIN M FORTE GEL", defaultCost: 45 },
  { name: "REXIDIN-M FORTE GEL", defaultCost: 82 },
  { name: "REXIDINE M FORTE GEL", defaultCost: 98 },
  { name: "ROOT CANAL TREAMENT PACKAGE WITH ZIRCONIUM CROWN", defaultCost: 12000 },
  { name: "ROOT CANAL TREATMENT - SESSION 1 (ACCESS OPENING )", defaultCost: 3000 },
  { name: "ROOT CANAL TREATMENT - SESSION 2 (BMP)", defaultCost: 4000 },
  { name: "ROOT CANAL TREATMENT WITH BIO CERAMIC SEALER", defaultCost: 0 },
  { name: "Root canal treatment with bio ceramic sealer ( CERASEAL )", defaultCost: 4000 },
  { name: "ROOT CANAL TREATMENT-SESSION 3 (OBTURATION)", defaultCost: 3000 },
  { name: "ROOT PLANNING", defaultCost: 0 },
  { name: "RPD REPAIR", defaultCost: 1000 },
  { name: "RPD CLASP REPAIR", defaultCost: 800 },
  { name: "rpd repair", defaultCost: 500 },
  { name: "RPD TRIMMING", defaultCost: 0 },
  { name: "RPD UPPER AND LOWER", defaultCost: 20000 },
  { name: "RPD-TOOTH ATTACHEMENT", defaultCost: 0 },
  { name: "SAFE ENDO TYPE", defaultCost: 9700 },
  { name: "SCALING (TOOTH CLEANING)", defaultCost: 1000 },
  { name: "SCALING WITH FLOUROSIS POLISHING", defaultCost: 1000 },
  { name: "SCALING WITH LASER DISINFECTION", defaultCost: 5000 },
  { name: "SCALING( TEETH CLEANING) AND TOOTH POLISHING", defaultCost: 1000 },
  { name: "SCANNING OF TEETH", defaultCost: 0 },
  { name: "SCANNING REPORTS", defaultCost: 200 },
  { name: "SCREW RETAINED CEMENTED CROWN WITH TITANIUM ABUTMENT", defaultCost: 5000 },
  { name: "SCREW RETAINED IMPLANT CERAMIC CROWN", defaultCost: 6000 },
  { name: "SCREW RETAINED IMPLANT ZIRCONIUM CROWN", defaultCost: 7000 },
  { name: "SENSODENT-K PLUS PASTE", defaultCost: 120 },
  { name: "SENSODYNE PASTE", defaultCost: 150 },
  { name: "SILVER AMALGAM - CAPSULE", defaultCost: 1000 },
  { name: "SM FIBRO CAPSULE", defaultCost: 300 },
  { name: "soft splint", defaultCost: 2000 },
  { name: "SPACE CLOSER BY LC COMPOSITE", defaultCost: 2000 },
  { name: "Space Maintainer", defaultCost: 0 },
  { name: "SPLINT - METAAL STRIPS", defaultCost: 4500 },
  { name: "SPLINT -METAL", defaultCost: 4500 },
  { name: "SPLINT REMOVAL", defaultCost: 0 },
  { name: "SPLINT REPAIR", defaultCost: 1000 },
  { name: "SPLINT WITH CO-AXIAL WIRE", defaultCost: 4500 },
  { name: "Splinting", defaultCost: 0 },
  { name: "STAINLESS STEEL CROWN", defaultCost: 2000 },
  { name: "STIM -FLOSSERS", defaultCost: 70 },
  { name: "stim brush", defaultCost: 0 },
  { name: "STIM FLOSS", defaultCost: 125 },
  { name: "STIM ORTHODONTIC BRUSH", defaultCost: 70 },
  { name: "stim unique ortho brush", defaultCost: 960 },
  { name: "SUGAR TEST", defaultCost: 50 },
  { name: "SURGICAL EXTRACTION", defaultCost: 1500 },
  { name: "SUTURE MATERIAL", defaultCost: 500 },
  { name: "SUTURE REMOVAL", defaultCost: 0 },
  { name: "TEMPORARY CAP", defaultCost: 500 },
  { name: "TEMPORARY FILLING", defaultCost: 300 },
  { name: "TEMPORARY FIXED TOOTH REPLACEMENT", defaultCost: 2000 },
  { name: "TONGUE TIE ( LINGUAL FRENECTOMY )", defaultCost: 15000 },
  { name: "TOOTH ATTHACHMENT FOR RPD", defaultCost: 500 },
  { name: "TOOTH MIN", defaultCost: 160 },
  { name: "TOOTH MODEL", defaultCost: 1000 },
  { name: "TOOTH POLISHING", defaultCost: 1000 },
  { name: "TOOTH REPLACEMENT BY COMPOSITE", defaultCost: 2000 },
  { name: "TOOTH REPLACEMENT BY DENTAL IMPLANT", defaultCost: 12000 },
  { name: "TOOTH REPLACEMENT BY SPLINT", defaultCost: 4500 },
  { name: "TOOTH REPLACEMENT FOR OLD DENTURE", defaultCost: 0 },
  { name: "TOOTH REPLACEMENT WITH FIBRE SPLINT", defaultCost: 4500 },
  { name: "TOOTH REPLACEMENT WITH FLEXI DENTURE", defaultCost: 10000 },
  { name: "Tooth replantation", defaultCost: 5000 },
  { name: "toothbrush", defaultCost: 100 },
  { name: "TOOTHMIN", defaultCost: 150 },
  { name: "TOOTHPASTE SENSODYNE REPAIR & PROTECT", defaultCost: 150 },
  { name: "TREATMENT DONE UNDER GENERAL ANAESTHESIA", defaultCost: 25000 },
  { name: "TURBOCART ONITMENT", defaultCost: 80 },
  { name: "twin block appliance", defaultCost: 5000 },
  { name: "upper and lower removable retainer", defaultCost: 3000 },
  { name: "UPPER FIXED FULL ARCH TEETH REPLACEMENT WITH HYBRID DENTURE- METAL BAR", defaultCost: 160000 },
  { name: "UPPER FULL ARCH REHABILATION BY IMPLANT PROSTHESIS", defaultCost: 150000 },
  { name: "UPPER FULL ARCH REHABILITATION", defaultCost: 120000 },
  { name: "UPPER FULL ARCH REHABILITATION WITH IMPLANT", defaultCost: 0 },
  { name: "UPPER HAWLEYS", defaultCost: 2500 },
  { name: "VANTEJ", defaultCost: 100 },
  { name: "VANTEJ PASTE", defaultCost: 100 },
  { name: "WATER FLOSS (ORAL B)", defaultCost: 0 },
  { name: "WIRE CHANGED ( 016 )", defaultCost: 1800 },
  { name: "wisdom tooth extraction", defaultCost: 3000 },
  { name: "ZINC OXIDE EUGENOL FILLING", defaultCost: 500 },
  { name: "ZIRCONIUM CROWN ( CAP )", defaultCost: 0 },
  { name: "ZIRCONIUM CROWN ( PREMIUM )", defaultCost: 10000 },
  { name: "ZIRCONIUM CROWN REPAIR", defaultCost: 2000 },
  { name: "ZIRCONIUM CROWN WITH INLAY", defaultCost: 7000 },
  { name: "ZIRCONIUM INLAY", defaultCost: 7000 },
];

export const DEFAULT_PROCEDURES_COUNT = 421;
