export const defaultReferralSources = [
  'Another Patient',
  'Just Dial',
  'Google',
  'MEDICAL',
  'LAXMI MEDICAL',
  'LKS',
  'DR.IQBAL',
  'KOUSIK',
  'KRISHNAN',
  'KOVAI TIMBER NIZAR',
  'JHON',
  'DR.PALLAVI',
  'Dr.PRIYA',
  'SISTER PRIYA',
  'DR.PRASANNA',
  'DR.PREM',
  'MEDICAL THATIL PHARMACY',
  'MEERAN',
  'ADAYAR CLINIC',
  'GOLDEN',
  'VANARAJ',
  'LAXMI MEDICAL GANDHI',
  'KANNIYAMMAL',
  'SISTER.JASMIN',
  'MOHAMED',
  'NAVAS GANI',
  'DR.EZILMARAN',
  'KOUSIQ',
  'SHARIFF',
  'CABLE',
  'MEDICAL MASS',
  'DR.PRABHAKAR',
  'Dr.MAARESWARAN',
  'DR.GOWRISHANKAR',
  'BRO.BENNETO',
  'Dr.MUBEEN',
  'CRESCENT COLLEGE',
  'SUNDARAM MEDICAL',
  'Dr.THOMAS',
  'Dr.GEETHAMANI',
  'S F MEDICAL',
  'Hameediya Shahul',
  'Shine Plastics',
  'Friend',
  'Family',
  'Social Media',
];