// PROCEDURES CATALOG SEED DATA
// Contains ~300 dental procedures with default prices.
// Import and run seedProceduresCatalog() once on first deploy.

export interface ProcedureSeed {
  name: string;
  cost: number;
  category: string;
}

export const PROCEDURES_CATALOG: ProcedureSeed[] = [
  { name: 'Consultation', cost: 300, category: 'Consultation' },
  { name: 'OPG AND CONSULTATION', cost: 500, category: 'Diagnostics' },
  { name: 'DIGITAL OPG ( 2D PAN i )', cost: 500, category: 'Diagnostics' },
  { name: 'ORTHOPANTOMOGRAM', cost: 500, category: 'Diagnostics' },
  { name: 'IOPA', cost: 300, category: 'Diagnostics' },
  { name: 'IOPA - RVG XRAY', cost: 300, category: 'Diagnostics' },
  { name: 'CBCT', cost: 1000, category: 'Diagnostics' },
  { name: 'CBCT AND OPG', cost: 1500, category: 'Diagnostics' },
  { name: 'SCANNING OF TEETH', cost: 0, category: 'Diagnostics' },
  { name: 'DIGITAL INTRA ORAL SCAN', cost: 2000, category: 'Diagnostics' },
  { name: 'SCANNING REPORTS', cost: 200, category: 'Diagnostics' },
  { name: '3D MODEL', cost: 1000, category: 'Diagnostics' },
  { name: 'DENTAL STONE MODEL', cost: 500, category: 'Diagnostics' },
  { name: 'SUGAR TEST', cost: 50, category: 'Diagnostics' },
  { name: 'blood sugar test', cost: 300, category: 'Diagnostics' },
  { name: 'AGE CERTIFICATE', cost: 0, category: 'Diagnostics' },
  { name: 'FA ORTHO CHECK UP', cost: 300, category: 'Diagnostics' },
  { name: 'FA CHECKUP', cost: 300, category: 'Orthodontics' },
  { name: 'FA ORTHO CHECK UP', cost: 300, category: 'Orthodontics' },
  { name: 'Extraction', cost: 1000, category: 'Extraction' },
  { name: 'MILK TEETH EXTRACTION', cost: 700, category: 'Extraction' },
  { name: 'EXTRACTION -TOOTH PART', cost: 500, category: 'Extraction' },
  { name: 'EXTRACTION - REMNANT TOOTH ROOT PART', cost: 1000, category: 'Extraction' },
  { name: 'SURGICAL EXTRACTION', cost: 1500, category: 'Extraction' },
  { name: 'wisdom tooth extraction', cost: 3000, category: 'Extraction' },
  { name: 'EXTRACTION WITH SUTURE', cost: 1000, category: 'Extraction' },
  { name: 'EXTRACTION FOLLOWED BY BONE GRAFT', cost: 3000, category: 'Extraction' },
  { name: 'EXTRACTION FOLLOWED BY COLLAGEN PLUG', cost: 2000, category: 'Extraction' },
  { name: 'IMPACTION FOLLOWED BY PLACEMENT OF COLLAGEN PLUG', cost: 10000, category: 'Extraction' },
  { name: 'EXTRACTION FRACTURED CROWN', cost: 1000, category: 'Extraction' },
  { name: 'EXTRACTION- PARA-MOLAR', cost: 1000, category: 'Extraction' },
  { name: 'NON OSSEOINTEGRATED IMPLANT AND CROWN REMOVAL', cost: 3000, category: 'Extraction' },
  { name: 'IMPLANT REMOVAL', cost: 5000, category: 'Extraction' },
  { name: 'IMPLANT EXPLANTATION', cost: 0, category: 'Extraction' },
  { name: 'plate removal', cost: 8000, category: 'Extraction' },
  { name: 'FILLING - GIC FILLING', cost: 600, category: 'Fillings' },
  { name: 'FILLING-GIC TYPE 9 EXTRA', cost: 800, category: 'Fillings' },
  { name: 'FILLING-GIC TYPE 9 EXTRA WITH DYCAL PULP CAPING', cost: 900, category: 'Fillings' },
  { name: 'FILLING-GIC LC', cost: 0, category: 'Fillings' },
  { name: 'FILLING- GIC FILLING', cost: 600, category: 'Fillings' },
  { name: 'FILLING- COMPOSITE RESIN', cost: 800, category: 'Fillings' },
  { name: 'FILLING - CIMPOSITE RESIN WITH DYCALPULP CAPING', cost: 1000, category: 'Fillings' },
  { name: 'FILLING - COMPOSITE RESIN - DYCAL BASE', cost: 1000, category: 'Fillings' },
  { name: 'FILLING- COMPOSITE RESIN - DYCAL BASE', cost: 1000, category: 'Fillings' },
  { name: 'COMPOSITE FILLING ( BUCCAL PIT )', cost: 400, category: 'Fillings' },
  { name: 'COMPOSITE BITE FOR PIT AND FISSURE', cost: 500, category: 'Fillings' },
  { name: 'pit and fissure sealant', cost: 500, category: 'Fillings' },
  { name: 'FILLING- ZNOE', cost: 300, category: 'Fillings' },
  { name: 'TEMPORARY FILLING', cost: 300, category: 'Fillings' },
  { name: 'FILLING-GIC TYPE 9 EXTRA CAPSULE', cost: 1000, category: 'Fillings' },
  { name: 'FILLING - TYPE 7 ( WHITE )', cost: 1000, category: 'Fillings' },
  { name: 'FILLING - TYPE 7 GC CAPSULE WHITE', cost: 1000, category: 'Fillings' },
  { name: 'FILLING- TYPE 7 (PINK )', cost: 1000, category: 'Fillings' },
  { name: 'GIC ( TYPE VII GLASS IONOMER CEMENT )', cost: 1000, category: 'Fillings' },
  { name: 'GIC FILLING - TYPE 7 CAPSULE PINK', cost: 1000, category: 'Fillings' },
  { name: 'FILLING - IONOFIL MOLAR', cost: 1000, category: 'Fillings' },
  { name: 'FILLING- IONOFIL- MOLAR', cost: 800, category: 'Fillings' },
  { name: 'FILLING-HY BOND RESIGLASS', cost: 1000, category: 'Fillings' },
  { name: 'LC COMPOSITE (IPS EMPRESS DIRECT)', cost: 2000, category: 'Fillings' },
  { name: 'LC COMPOSITE (IVOCLARVIVADENT)', cost: 0, category: 'Fillings' },
  { name: 'FILLING- CERVICAL CARIES', cost: 500, category: 'Fillings' },
  { name: 'CERVICAL ABRASION FILLING', cost: 500, category: 'Fillings' },
  { name: 'CERVICAL ABRASION FILLING 162636', cost: 1500, category: 'Fillings' },
  { name: 'ABRASION', cost: 0, category: 'Fillings' },
  { name: 'PULP CAPPING + IONOSEAL + COMPOSITE FILLING', cost: 1000, category: 'Fillings' },
  { name: 'DUAL RESTORATION', cost: 1000, category: 'Fillings' },
  { name: 'CAVITY FILLING', cost: 1000, category: 'Fillings' },
  { name: 'FILLINGS', cost: 1000, category: 'Fillings' },
  { name: 'CORE FILLING', cost: 1500, category: 'Fillings' },
  { name: 'CORE FILLING - METAL', cost: 1500, category: 'Fillings' },
  { name: 'CORE BUILD-UP', cost: 0, category: 'Fillings' },
  { name: 'ENTRANCE FILLING - AMALGAM CAPSULE', cost: 1000, category: 'Fillings' },
  { name: 'SILVER AMALGAM - CAPSULE', cost: 1000, category: 'Fillings' },
  { name: 'ENTRANCE FILLING (COMPOSITE)', cost: 1000, category: 'Fillings' },
  { name: 'ZINC OXIDE EUGENOL FILLING', cost: 500, category: 'Fillings' },
  { name: 'DRY SOCKET- ZnOE PACK', cost: 300, category: 'Fillings' },
  { name: 'FILLING-I SEAL', cost: 0, category: 'Fillings' },
  { name: 'FILLING-TF', cost: 0, category: 'Fillings' },
  { name: 'FILLING-COMPOSITE', cost: 0, category: 'Fillings' },
  { name: 'GAP FILLING', cost: 200, category: 'Fillings' },
  { name: 'SAFE ENDO TYPE 9', cost: 700, category: 'Fillings' },
  { name: 'FILLING- CAPSULE EQUA FORTE', cost: 1000, category: 'Fillings' },
  { name: 'Filling or root canal treatment', cost: 4000, category: 'Fillings' },
  { name: 'SPACE CLOSER BY LC COMPOSITE', cost: 2000, category: 'Fillings' },
  { name: 'MID-LINE DIASTEMA CLOSER BY IPS-EMPRESS DIRECT', cost: 3500, category: 'Fillings' },
  { name: 'COMPOSITE-MID LINE DIASTEMA REPEAT WORK', cost: 500, category: 'Fillings' },
  { name: 'ROOT CANAL TREATMENT - SESSION 1 (ACCESS OPENING )', cost: 3000, category: 'Root Canal' },
  { name: 'ROOT CANAL TREATMENT - SESSION 2 (BMP)', cost: 4000, category: 'Root Canal' },
  { name: 'ROOT CANAL TREATMENT-SESSION 3 (OBTURATION)', cost: 3000, category: 'Root Canal' },
  { name: 'ROOT CANAL TREATMENT WITH BIO CERAMIC SEALER', cost: 4000, category: 'Root Canal' },
  { name: 'Root canal treatment with bio ceramic sealer ( CERASEAL )', cost: 4000, category: 'Root Canal' },
  { name: 'RCT-CLOSED DRESSING', cost: 0, category: 'Root Canal' },
  { name: 'RCT-OBTURATION', cost: 0, category: 'Root Canal' },
  { name: 'RE ROOT CANAL TREAMENT', cost: 4500, category: 'Root Canal' },
  { name: 'RE TREATMENT - RCT WITH CERASEAL', cost: 4500, category: 'Root Canal' },
  { name: 'RE- ROOT CANAL TREATMENT WITH BIO CERAMIC SEALER - CERASEAL', cost: 4500, category: 'Root Canal' },
  { name: 'MTA PLACEMENT', cost: 1500, category: 'Root Canal' },
  { name: 'PULPOTOMY', cost: 1500, category: 'Root Canal' },
  { name: 'PULPECTOMY', cost: 3000, category: 'Root Canal' },
  { name: 'PULP THERAPY', cost: 0, category: 'Root Canal' },
  { name: 'PULPTOMY', cost: 1500, category: 'Root Canal' },
  { name: 'PULPECTOMY WITH STAINLESS STEEL CROWN', cost: 5000, category: 'Root Canal' },
  { name: 'PULPECTOMY + COMPOSITE FILLING', cost: 3500, category: 'Root Canal' },
  { name: 'PULP THERAPY WITH STAINLESS STEEL CROWN', cost: 5000, category: 'Root Canal' },
  { name: 'PULPOTOMY WITH STAINLESS STEEL CROWN', cost: 0, category: 'Root Canal' },
  { name: 'METAL CROWN', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'STAINLESS STEEL CROWN', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'CERAMIC CROWN (CAD-CAM)', cost: 4000, category: 'Crowns & Bridges' },
  { name: 'DMLS- CERAMIC CROWN ( CAD CAM)', cost: 5000, category: 'Crowns & Bridges' },
  { name: 'CERAMIC CROWN ( CAP ) -P', cost: 3500, category: 'Crowns & Bridges' },
  { name: 'CERMAIC CROWN (CAP)-P', cost: 4000, category: 'Crowns & Bridges' },
  { name: 'CERAMIC FACING CROWN', cost: 0, category: 'Crowns & Bridges' },
  { name: 'PORCELAIN JACKET', cost: 5000, category: 'Crowns & Bridges' },
  { name: 'ZIRCONIUM CROWN ( CAP )', cost: 7000, category: 'Crowns & Bridges' },
  { name: 'ZIRCONIUM CROWN ( PREMIUM )', cost: 10000, category: 'Crowns & Bridges' },
  { name: 'CROWN- ZIRCONIUM', cost: 7000, category: 'Crowns & Bridges' },
  { name: 'DENTCARE ZIRCONIA SUPER TRANSLUCENT', cost: 10000, category: 'Crowns & Bridges' },
  { name: 'ZIRCONIUM CROWN REPAIR', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'CERAMIC CROWN REPAIR', cost: 1000, category: 'Crowns & Bridges' },
  { name: 'CERAMIC CROWN REPEAT WORK', cost: 1000, category: 'Crowns & Bridges' },
  { name: 'CROWN', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'CROWN- ACRALIC', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'ACRYLIC CROWN', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'PMMA CROWN', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'PMMA CROWN AND BRIDGE', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'DMLS METAL CROWN', cost: 2500, category: 'Crowns & Bridges' },
  { name: 'G - CAM CROWN', cost: 6000, category: 'Crowns & Bridges' },
  { name: 'G-CAM CROWN', cost: 8000, category: 'Crowns & Bridges' },
  { name: 'ENDOCROWN', cost: 10000, category: 'Crowns & Bridges' },
  { name: 'FPD METAL', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'FPD CERAMIC-P', cost: 3500, category: 'Crowns & Bridges' },
  { name: 'FPD ZIRCONIUM CERAMIC', cost: 7000, category: 'Crowns & Bridges' },
  { name: 'FPD ACRALIC', cost: 1500, category: 'Crowns & Bridges' },
  { name: 'FPD ACRLIC', cost: 1500, category: 'Crowns & Bridges' },
  { name: 'FPD ACRALIC FACING- METAL', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'INTERIM CROWN AND BRIDGE', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'CROWN AND BRIDGE', cost: 4000, category: 'Crowns & Bridges' },
  { name: 'CROWN AND BRIDGE REFIXATION', cost: 700, category: 'Crowns & Bridges' },
  { name: 'MARYLAND BRIDGE - ZIRCONIUM', cost: 0, category: 'Crowns & Bridges' },
  { name: 'MARYLAND BRIDGE- CERAMIC', cost: 0, category: 'Crowns & Bridges' },
  { name: 'MALO BRIDGE', cost: 0, category: 'Crowns & Bridges' },
  { name: 'TEMPORARY CAP', cost: 500, category: 'Crowns & Bridges' },
  { name: 'TEMPORARY FIXED TOOTH REPLACEMENT', cost: 2000, category: 'Crowns & Bridges' },
  { name: 'Provisional fixed partial denture', cost: 25000, category: 'Crowns & Bridges' },
  { name: 'CAP FIXATION', cost: 0, category: 'Crowns & Bridges' },
  { name: 'CROWN REFIXATION', cost: 500, category: 'Crowns & Bridges' },
  { name: 'CAP REFIXATION', cost: 1000, category: 'Crowns & Bridges' },
  { name: 'METAL CROWN REFIXATION', cost: 500, category: 'Crowns & Bridges' },
  { name: 'CERMAIC CROWN (CAP)- REFIXATION', cost: 500, category: 'Crowns & Bridges' },
  { name: 'FPD REFIXATION', cost: 600, category: 'Crowns & Bridges' },
  { name: 'FPD CERAMIC REFIXATION', cost: 1000, category: 'Crowns & Bridges' },
  { name: 'REFIXATION-ZIRCONIUM CROWN/FPD', cost: 500, category: 'Crowns & Bridges' },
  { name: 'FPD REMOVAL', cost: 500, category: 'Crowns & Bridges' },
  { name: 'CROWN REMOVAL', cost: 500, category: 'Crowns & Bridges' },
  { name: 'CROWN LENGTHENING', cost: 0, category: 'Crowns & Bridges' },
  { name: 'LASER CROWN LENGTHENING', cost: 3000, category: 'Crowns & Bridges' },
  { name: 'OCCLUSAL REDUCTION IN OLD CAP', cost: 500, category: 'Crowns & Bridges' },
  { name: 'OLD CROWN SCREW ACCESS CREATED FOR IMPLANT AND CROWN ACCESS FILLING DONE', cost: 1500, category: 'Crowns & Bridges' },
  { name: 'crowm material', cost: 1500, category: 'Crowns & Bridges' },
  { name: 'Dental Implant', cost: 15000, category: 'Implants' },
  { name: 'TOOTH REPLACEMENT BY DENTAL IMPLANT', cost: 12000, category: 'Implants' },
  { name: 'IMPLANT - ADIN', cost: 15000, category: 'Implants' },
  { name: 'ABUTMENT ADIN', cost: 2500, category: 'Implants' },
  { name: 'ABUTMENT -ADIN', cost: 3000, category: 'Implants' },
  { name: 'IMPLANT CROWN', cost: 6000, category: 'Implants' },
  { name: 'IMPLANT CROWN - ZIRCONIUM', cost: 8000, category: 'Implants' },
  { name: 'IMPLANT CROWN WITH ABUTMENT - CERAMIC', cost: 5000, category: 'Implants' },
  { name: 'SCREW RETAINED CEMENTED CROWN WITH TITANIUM ABUTMENT', cost: 5000, category: 'Implants' },
  { name: 'SCREW RETAINED IMPLANT ZIRCONIUM CROWN', cost: 7000, category: 'Implants' },
  { name: 'SCREW RETAINED IMPLANT CERAMIC CROWN', cost: 6000, category: 'Implants' },
  { name: 'IMPLANT-SCREW RETAINED CROWN ACCESS FILLING', cost: 1500, category: 'Implants' },
  { name: 'IMPLANT ABUTMENT', cost: 5000, category: 'Implants' },
  { name: 'METAL ABUTMENR', cost: 3000, category: 'Implants' },
  { name: 'ABUTMENT + CERAMIC CROWN', cost: 6000, category: 'Implants' },
  { name: 'ABUTMENT+ZIRCONIUM CROWN', cost: 9000, category: 'Implants' },
  { name: 'MULTIUNIT ABUTMENT', cost: 0, category: 'Implants' },
  { name: 'CUSTOMIZE ABUTMENT', cost: 0, category: 'Implants' },
  { name: 'ABUTMENT SCREW CHANGED', cost: 5000, category: 'Implants' },
  { name: 'HEALING CAP', cost: 2000, category: 'Implants' },
  { name: 'IMPLANT TEMP CROWN', cost: 2000, category: 'Implants' },
  { name: 'IMPLANT TEMPORARY TOOTH REPLACEMENT', cost: 2000, category: 'Implants' },
  { name: 'IMPLANT WITH TOOTH REPLACEMENT', cost: 0, category: 'Implants' },
  { name: 'DENTAL IMPLANT WITH ATTACHMENT', cost: 20000, category: 'Implants' },
  { name: 'IMPLANT WITH ATTCHMENT AND CROWN', cost: 25000, category: 'Implants' },
  { name: 'ball head implant and attachment', cost: 15000, category: 'Implants' },
  { name: 'NOBEL BIOCARE IMPLANT', cost: 35000, category: 'Implants' },
  { name: 'NOBEL BIOCARE DENTAL IMPLANT', cost: 35000, category: 'Implants' },
  { name: 'PTERYGOID IMPLANT', cost: 25000, category: 'Implants' },
  { name: 'BI CORTICAL IMPLANT', cost: 20000, category: 'Implants' },
  { name: 'BASAL IMPLANT', cost: 20000, category: 'Implants' },
  { name: 'IMPLANT OVER DENTURE REFIXING', cost: 1500, category: 'Implants' },
  { name: 'IMPLANT- METAL BAR', cost: 15000, category: 'Implants' },
  { name: 'IMPLANT- METAL BAR WITH HYBRID TEETH', cost: 30000, category: 'Implants' },
  { name: 'IMPLANT - HYBRID TEETH SET WITH METAL BAR', cost: 10000, category: 'Implants' },
  { name: 'IMPLANT- INTERIM TEETH', cost: 5000, category: 'Implants' },
  { name: 'IMPLANT CROWN - CERAMIC CAT-CAM', cost: 5000, category: 'Implants' },
  { name: 'UPPER FULL ARCH REHABILITATION WITH IMPLANT', cost: 0, category: 'Implants' },
  { name: 'UPPER FULL ARCH REHABILATION BY IMPLANT PROSTHESIS', cost: 150000, category: 'Implants' },
  { name: 'LOWER FULL ARCH REHABILATION BY IMPLANT PROSTHESIS', cost: 150000, category: 'Implants' },
  { name: 'ANTERIOR TOOTH REPLACEMENT BY IMPLANT - CERAMIC CROWN AFTER 3 MONTHS', cost: 60000, category: 'Implants' },
  { name: 'ANTERIOR TOOTH REPLACEMENT BY IMPLANT - ZIRCONIUM CROWN AFTER 3 MONTHS', cost: 65000, category: 'Implants' },
  { name: 'COMPLETE DENTURE UPPER', cost: 10000, category: 'Dentures' },
  { name: 'COMPLETE DENTURE- LOWER', cost: 10000, category: 'Dentures' },
  { name: 'complete denture', cost: 25000, category: 'Dentures' },
  { name: 'Removal Full Mouth Complete Denture', cost: 20000, category: 'Dentures' },
  { name: 'DENTURE UPPER AND LOWER JAW', cost: 20000, category: 'Dentures' },
  { name: 'COMPLETE DENTURE REPAIR', cost: 1000, category: 'Dentures' },
  { name: 'DENTURE REPAIR', cost: 500, category: 'Dentures' },
  { name: 'DENTURE REPAIR - UPPER', cost: 2000, category: 'Dentures' },
  { name: 'DENTURE BASE', cost: 1000, category: 'Dentures' },
  { name: 'REMOVABLE DENTURE BASE', cost: 1000, category: 'Dentures' },
  { name: 'DENTURE TRIMMING', cost: 500, category: 'Dentures' },
  { name: 'DENTURE HARD LINER', cost: 2000, category: 'Dentures' },
  { name: 'Removal Partial Dentures', cost: 500, category: 'Dentures' },
  { name: 'TOOTH REPLACEMENT WITH FLEXI DENTURE', cost: 10000, category: 'Dentures' },
  { name: 'REMOVABLE PARTIAL DENTURE 5', cost: 5000, category: 'Dentures' },
  { name: 'RPD UPPER AND LOWER', cost: 20000, category: 'Dentures' },
  { name: 'RPD CLASP REPAIR', cost: 800, category: 'Dentures' },
  { name: 'rpd repair', cost: 500, category: 'Dentures' },
  { name: 'RPD REPAIR', cost: 1000, category: 'Dentures' },
  { name: 'RPD TRIMMING', cost: 0, category: 'Dentures' },
  { name: 'Cast Partial Denture', cost: 0, category: 'Dentures' },
  { name: 'TOOTH REPLACEMENT FOR OLD DENTURE', cost: 0, category: 'Dentures' },
  { name: 'REMOVABLE TOOTH REPLACEMENT', cost: 1000, category: 'Dentures' },
  { name: 'REMOVABLE TOOTH REPLACEMENT UPPER & LOWER', cost: 0, category: 'Dentures' },
  { name: 'INTERIM DENTURE', cost: 20000, category: 'Dentures' },
  { name: 'I BAR WITH INTERIM TEETH', cost: 20000, category: 'Dentures' },
  { name: 'HYBRID TEETH', cost: 0, category: 'Dentures' },
  { name: 'UPPER FIXED FULL ARCH TEETH REPLACEMENT WITH HYBRID DENTURE- METAL BAR', cost: 160000, category: 'Dentures' },
  { name: 'LOWER FIXED FULL ARCH TEETH REPLACEMENT WITH HYBRID DENTURE- METAL BAR', cost: 160000, category: 'Dentures' },
  { name: 'UPPER FULL ARCH REHABILITATION', cost: 120000, category: 'Dentures' },
  { name: 'INTERIM TEETH', cost: 2000, category: 'Dentures' },
  { name: 'SCALING( TEETH CLEANING) AND TOOTH POLISHING', cost: 1000, category: 'Periodontics' },
  { name: 'SCALING (TOOTH CLEANING)', cost: 1000, category: 'Periodontics' },
  { name: 'FULL MOUTH ORAL PROPHYLAXIS', cost: 2000, category: 'Periodontics' },
  { name: 'ORAL PROPHYLAXIS', cost: 2000, category: 'Periodontics' },
  { name: 'TOOTH POLISHING', cost: 1000, category: 'Periodontics' },
  { name: 'AIRFLOW SCALING', cost: 3000, category: 'Periodontics' },
  { name: 'SCALING WITH FLOUROSIS POLISHING', cost: 1000, category: 'Periodontics' },
  { name: 'SCALING WITH LASER DISINFECTION', cost: 5000, category: 'Periodontics' },
  { name: 'gingival curettage', cost: 4800, category: 'Periodontics' },
  { name: 'Flap surgery', cost: 10000, category: 'Periodontics' },
  { name: 'Flap Surgery with Graft', cost: 0, category: 'Periodontics' },
  { name: 'FLAP INCISION', cost: 200, category: 'Periodontics' },
  { name: 'PERI APICAL SURGERY', cost: 3000, category: 'Periodontics' },
  { name: 'GINGIVECTOMY', cost: 0, category: 'Periodontics' },
  { name: 'GINGIVOPLASTY', cost: 0, category: 'Periodontics' },
  { name: 'LASER POCKET DISINFECTION', cost: 10000, category: 'Periodontics' },
  { name: 'LASER DE PIGMENTATION', cost: 5000, category: 'Periodontics' },
  { name: 'FRENECTOMY', cost: 2000, category: 'Periodontics' },
  { name: 'LINGUAL FRENECTOMY', cost: 4500, category: 'Periodontics' },
  { name: 'LASER FRENECTOMY', cost: 5000, category: 'Periodontics' },
  { name: 'TONGUE TIE ( LINGUAL FRENECTOMY )', cost: 15000, category: 'Periodontics' },
  { name: 'OPERCULECTOMY', cost: 1000, category: 'Periodontics' },
  { name: 'OPERTCULECTOMY', cost: 1000, category: 'Periodontics' },
  { name: 'LASER OPERCULECTOMY', cost: 2000, category: 'Periodontics' },
  { name: 'PERI CORONAL FLAP EXCISION', cost: 1000, category: 'Periodontics' },
  { name: 'CROWN LENGTHENING', cost: 0, category: 'Periodontics' },
  { name: 'ALVEOPLASTY', cost: 1000, category: 'Periodontics' },
  { name: 'BONY SPICULES', cost: 500, category: 'Periodontics' },
  { name: 'BONE TRIMMING', cost: 1000, category: 'Periodontics' },
  { name: 'ROOT PLANNING', cost: 0, category: 'Periodontics' },
  { name: 'FA-METAL', cost: 20000, category: 'Orthodontics' },
  { name: 'FA-TOOTH COLOUR', cost: 20000, category: 'Orthodontics' },
  { name: 'FA-SELF LIGATING METAL', cost: 35000, category: 'Orthodontics' },
  { name: 'FA-SELF LIGATING -TOOTH COLOUR', cost: 45000, category: 'Orthodontics' },
  { name: 'FA-SELF LIGATING SMART CLIP - 3M', cost: 65000, category: 'Orthodontics' },
  { name: 'FA-LINGUAL', cost: 45000, category: 'Orthodontics' },
  { name: 'FIXED APPILANCE - METAL', cost: 27000, category: 'Orthodontics' },
  { name: 'MALOCCLUSION CORRECTION', cost: 45000, category: 'Orthodontics' },
  { name: 'MALOCCLUSION CORRECTION-3M', cost: 50000, category: 'Orthodontics' },
  { name: 'DAMON MALOCCLUSION CORRECTION', cost: 60000, category: 'Orthodontics' },
  { name: 'CLEAR ALIGNER', cost: 0, category: 'Orthodontics' },
  { name: 'ALIGNER', cost: 0, category: 'Orthodontics' },
  { name: 'INVISALIGN', cost: 0, category: 'Orthodontics' },
  { name: 'INVISALIGN GO', cost: 120000, category: 'Orthodontics' },
  { name: 'nvisalign® Clear Aligners & Teeth Straightening', cost: 150000, category: 'Orthodontics' },
  { name: 'EASY ORTHO', cost: 2000, category: 'Orthodontics' },
  { name: 'DEBONDING', cost: 2000, category: 'Orthodontics' },
  { name: 'BRACKET RE FIXATION', cost: 500, category: 'Orthodontics' },
  { name: 'BRACKET REMOVAL', cost: 1500, category: 'Orthodontics' },
  { name: 'MOLAR BAND LUTING', cost: 0, category: 'Orthodontics' },
  { name: 'BAND REFIXATION', cost: 300, category: 'Orthodontics' },
  { name: 'ARCH WIRE', cost: 600, category: 'Orthodontics' },
  { name: 'HAWLEYS', cost: 4000, category: 'Orthodontics' },
  { name: 'UPPER HAWLEYS', cost: 2500, category: 'Orthodontics' },
  { name: 'LOWER HAWLEYS', cost: 2500, category: 'Orthodontics' },
  { name: 'HAWLEYS WITH ANTERIOR BITE PLANE', cost: 5000, category: 'Orthodontics' },
  { name: 'removable retainer', cost: 2500, category: 'Orthodontics' },
  { name: 'upper and lower removable retainer', cost: 3000, category: 'Orthodontics' },
  { name: 'PREMIUM- upper and lower removable retainer', cost: 6000, category: 'Orthodontics' },
  { name: 'fixed retainer', cost: 3500, category: 'Orthodontics' },
  { name: 'FIXED & REMOVABLE RETAINER', cost: 5000, category: 'Orthodontics' },
  { name: 'Anterior Spilinting', cost: 3500, category: 'Orthodontics' },
  { name: 'RETAINER CORRECTION', cost: 500, category: 'Orthodontics' },
  { name: 'retainer removal', cost: 800, category: 'Orthodontics' },
  { name: 'ortho continous treatment', cost: 6000, category: 'Orthodontics' },
  { name: 'ORTHO IMPRESSION', cost: 1000, category: 'Orthodontics' },
  { name: 'ANTERIOR CROSSBITE CORRECTION', cost: 0, category: 'Orthodontics' },
  { name: 'ANTERIOR BITE PLAN', cost: 5000, category: 'Orthodontics' },
  { name: 'removable anterior biteplan', cost: 5000, category: 'Orthodontics' },
  { name: 'POSTERIOR BITE PLANE', cost: 50000, category: 'Orthodontics' },
  { name: 'twin block appliance', cost: 5000, category: 'Orthodontics' },
  { name: 'CHIN CAP', cost: 2000, category: 'Orthodontics' },
  { name: 'CHIN CUP APPLIANCE', cost: 5000, category: 'Orthodontics' },
  { name: 'MYOFUNCTIONAL APPLIANCE', cost: 5000, category: 'Orthodontics' },
  { name: 'MYOFUNCTIONAL APPLIANCE ( T4 K)', cost: 5000, category: 'Orthodontics' },
  { name: 'ORAL SCREEN', cost: 2500, category: 'Orthodontics' },
  { name: 'LIP BUMPER', cost: 2000, category: 'Orthodontics' },
  { name: 'F A', cost: 4000, category: 'Orthodontics' },
  { name: 'HABIT BREAKING APPLIANCE', cost: 0, category: 'Orthodontics' },
  { name: 'FIXED TOUNGE GRIP APPLIANCE', cost: 3500, category: 'Orthodontics' },
  { name: 'Space Maintainer', cost: 0, category: 'Orthodontics' },
  { name: 'BLEACHING TRAY', cost: 2000, category: 'Bleaching & Cosmetics' },
  { name: 'BLEACHING SYRINGE (GEL)', cost: 2000, category: 'Bleaching & Cosmetics' },
  { name: 'BLEACHING BOOST', cost: 8000, category: 'Bleaching & Cosmetics' },
  { name: 'BLANCONE BLEACH', cost: 15000, category: 'Bleaching & Cosmetics' },
  { name: 'BLANCONE POWER TOOTH WHITENING', cost: 15000, category: 'Bleaching & Cosmetics' },
  { name: 'FULL MOUTH ENAMELOPLASTY', cost: 1000, category: 'Bleaching & Cosmetics' },
  { name: 'ENAMELOPLASTY', cost: 200, category: 'Bleaching & Cosmetics' },
  { name: 'CORONOPLASTY', cost: 5000, category: 'Bleaching & Cosmetics' },
  { name: 'Laminates & Veneers', cost: 7000, category: 'Bleaching & Cosmetics' },
  { name: 'LIGHT CURE COMPOSITE VENEER', cost: 1000, category: 'Bleaching & Cosmetics' },
  { name: 'PORCELINE LAMINATE', cost: 15000, category: 'Bleaching & Cosmetics' },
  { name: 'FLAP INCISION', cost: 200, category: 'Oral Surgery' },
  { name: 'incision and drainge', cost: 100, category: 'Oral Surgery' },
  { name: 'EXCISION', cost: 2500, category: 'Oral Surgery' },
  { name: 'LASER EXCISION', cost: 5000, category: 'Oral Surgery' },
  { name: 'BIOPSY', cost: 2000, category: 'Oral Surgery' },
  { name: 'MUCOCELE SURIGICAL EXCISION', cost: 4500, category: 'Oral Surgery' },
  { name: 'CYST ENUCLEATION', cost: 4000, category: 'Oral Surgery' },
  { name: 'CYST ENUCLEATION AND MARSUPIALIZATION', cost: 10000, category: 'Oral Surgery' },
  { name: 'MARSUPIALIZATION', cost: 0, category: 'Oral Surgery' },
  { name: 'NOVABONE PUTTY', cost: 8000, category: 'Oral Surgery' },
  { name: 'NOVABONE (Bioactive synthetic bone graft)', cost: 8000, category: 'Oral Surgery' },
  { name: 'BONE GRAFT', cost: 0, category: 'Oral Surgery' },
  { name: 'BONE GRAFT PLACED & LASER TREATMENT DONE FOR DISINFECTION', cost: 30000, category: 'Oral Surgery' },
  { name: 'EXTRACTION FOLLOWED BY BONE GRAFT', cost: 3000, category: 'Oral Surgery' },
  { name: 'BIO -OSS(COLLOGEN)', cost: 5000, category: 'Oral Surgery' },
  { name: 'BIO OSS', cost: 9700, category: 'Oral Surgery' },
  { name: 'BONE SUBSTITUE - GEISTLICH BIO-Oss( SPONGIOUS GRANULES)', cost: 15000, category: 'Oral Surgery' },
  { name: 'Bone substitute material', cost: 1200, category: 'Oral Surgery' },
  { name: 'COLLAGEN PLUG', cost: 1000, category: 'Oral Surgery' },
  { name: 'SUTURE REMOVAL', cost: 0, category: 'Oral Surgery' },
  { name: 'SUTURE MATERIAL', cost: 500, category: 'Oral Surgery' },
  { name: 'ABSORBABLE SUTURE', cost: 600, category: 'Oral Surgery' },
  { name: 'TREATMENT DONE UNDER GENERAL ANAESTHESIA', cost: 25000, category: 'Oral Surgery' },
  { name: 'ARCH BAR FIXATION', cost: 50000, category: 'Oral Surgery' },
  { name: 'DENTOALVEOLAR FRACTURE MANAGEMENT WITH ARCH BAR', cost: 30000, category: 'Oral Surgery' },
  { name: 'MINOR SURGICAL PROCEDURE ( ALVEOLAR FRACTURE MANAGEMENT WITH ARCH BAR ,MICRO SUTURING DONE FOR UPPER LIP TEAR)', cost: 48000, category: 'Oral Surgery' },
  { name: 'DENTO ALVELOLAR # LOWER', cost: 0, category: 'Oral Surgery' },
  { name: 'Splinting', cost: 0, category: 'Splinting' },
  { name: 'caps splint', cost: 1500, category: 'Splinting' },
  { name: 'SPLINT -METAL', cost: 4500, category: 'Splinting' },
  { name: 'SPLINT - METAAL STRIPS', cost: 4500, category: 'Splinting' },
  { name: 'SPLINT WITH CO-AXIAL WIRE', cost: 4500, category: 'Splinting' },
  { name: 'CAP SPLINT WITH ANTERIOR BITE PLANE', cost: 3000, category: 'Splinting' },
  { name: 'CAP SPLINT WITH TOOTH REPLACEMENT', cost: 1500, category: 'Splinting' },
  { name: 'HARD SPLINT RETAINER', cost: 2000, category: 'Splinting' },
  { name: 'soft splint', cost: 2000, category: 'Splinting' },
  { name: 'Hard Splint 1mm', cost: 1500, category: 'Splinting' },
  { name: 'HYBRID SMART MOUTH GUARD', cost: 5000, category: 'Splinting' },
  { name: 'SPLINT REPAIR', cost: 1000, category: 'Splinting' },
  { name: 'SPLINT REMOVAL', cost: 0, category: 'Splinting' },
  { name: 'TOOTH REPLACEMENT BY SPLINT', cost: 4500, category: 'Splinting' },
  { name: 'TOOTH REPLACEMENT WITH FIBRE SPLINT', cost: 4500, category: 'Splinting' },
  { name: 'INLAY-METAL', cost: 2000, category: 'Inlays & Posts' },
  { name: 'inlay', cost: 1000, category: 'Inlays & Posts' },
  { name: 'ZIRCONIUM INLAY', cost: 7000, category: 'Inlays & Posts' },
  { name: 'ZIRCONIUM CROWN WITH INLAY', cost: 7000, category: 'Inlays & Posts' },
  { name: 'CERAIMC CROWN WITH INLAY', cost: 4500, category: 'Inlays & Posts' },
  { name: 'G-CAM INLAY', cost: 0, category: 'Inlays & Posts' },
  { name: 'INLAY REFIXING', cost: 1000, category: 'Inlays & Posts' },
  { name: 'POST-FIBRE', cost: 2000, category: 'Inlays & Posts' },
  { name: 'POST', cost: 2000, category: 'Inlays & Posts' },
  { name: 'POST &CORE', cost: 2000, category: 'Inlays & Posts' },
  { name: 'METAL POST', cost: 1500, category: 'Inlays & Posts' },
  { name: 'METAL COPPING', cost: 1500, category: 'Inlays & Posts' },
  { name: 'POST REFIXATION', cost: 1000, category: 'Inlays & Posts' },
  { name: 'Laser disinfection', cost: 7000, category: 'Laser' },
  { name: 'LASER DE PIGMENTATION', cost: 5000, category: 'Laser' },
  { name: 'LASER POCKET DISINFECTION', cost: 10000, category: 'Laser' },
  { name: 'LASER CROWN LENGTHENING', cost: 3000, category: 'Laser' },
  { name: 'LASER FRENECTOMY', cost: 5000, category: 'Laser' },
  { name: 'LASER OPERCULECTOMY', cost: 2000, category: 'Laser' },
  { name: 'LASER EXCISION', cost: 5000, category: 'Laser' },
  { name: 'SCALING WITH LASER DISINFECTION', cost: 5000, category: 'Laser' },
  { name: 'BONE GRAFT PLACED & LASER TREATMENT DONE FOR DISINFECTION', cost: 30000, category: 'Laser' },
  { name: 'Fluroide Application', cost: 0, category: 'Preventive' },
  { name: 'FLOURIDE VARNISH', cost: 500, category: 'Preventive' },
  { name: 'FLUORIDE VARNISH', cost: 1000, category: 'Preventive' },
  { name: 'ORAL -B SESITIVE SUPER THIN', cost: 50, category: 'Products' },
  { name: 'CHEERIO', cost: 70, category: 'Products' },
  { name: 'TOOTHMIN', cost: 150, category: 'Products' },
  { name: 'ORTHODONTIC BRUSH', cost: 50, category: 'Products' },
  { name: 'ORAHEX PLUS MOUTHWASH', cost: 60, category: 'Products' },
  { name: 'CLOHEX PLUS MOUTHWASH', cost: 90, category: 'Products' },
  { name: 'SENSODYNE PASTE', cost: 150, category: 'Products' },
  { name: 'HYDENT-K PASTE', cost: 80, category: 'Products' },
  { name: 'VANTEJ PASTE', cost: 100, category: 'Products' },
  { name: 'SENSODENT-K PLUS PASTE', cost: 120, category: 'Products' },
  { name: 'COLGATE PASTE', cost: 100, category: 'Products' },
  { name: 'STIM -FLOSSERS', cost: 70, category: 'Products' },
  { name: 'FLOSAL-32', cost: 100, category: 'Products' },
  { name: 'TURBOCART ONITMENT', cost: 80, category: 'Products' },
  { name: 'REXIDIN M FORTE GEL', cost: 45, category: 'Products' },
  { name: 'STIM ORTHODONTIC BRUSH', cost: 70, category: 'Products' },
  { name: 'ORAL -B TOOTH BRUSH', cost: 50, category: 'Products' },
  { name: 'ORAL-B TOOTH BRUSH FOR KIDS', cost: 40, category: 'Products' },
  { name: 'SM FIBRO CAPSULE', cost: 300, category: 'Products' },
  { name: 'stim brush', cost: 0, category: 'Products' },
  { name: 'STIM FLOSS', cost: 125, category: 'Products' },
  { name: 'STIM-FLOSSERS', cost: 125, category: 'Products' },
  { name: 'INTERDENTAL BRUSH', cost: 180, category: 'Products' },
  { name: 'toothbrush', cost: 100, category: 'Products' },
  { name: 'AMFLOR MOUTHWASH', cost: 200, category: 'Products' },
  { name: 'Polident', cost: 300, category: 'Products' },
  { name: 'DENTURE ADHESIVE', cost: 315, category: 'Products' },
  { name: 'REXIDIN-M FORTE GEL', cost: 82, category: 'Products' },
  { name: 'REXIDINE M FORTE GEL', cost: 98, category: 'Products' },
  { name: 'GEL METROHEX', cost: 30, category: 'Products' },
  { name: 'KIDODENT XP', cost: 180, category: 'Products' },
  { name: 'HYDENT PRO', cost: 150, category: 'Products' },
  { name: 'TOOTHPASTE SENSODYNE REPAIR & PROTECT', cost: 150, category: 'Products' },
  { name: 'TOOTH MIN', cost: 160, category: 'Products' },
  { name: 'ORTHO- BRUSH', cost: 100, category: 'Products' },
  { name: 'VANTEJ', cost: 100, category: 'Products' },
  { name: 'stim unique ortho brush', cost: 960, category: 'Products' },
  { name: 'FULL MOUTH REHABILITATION', cost: 0, category: 'Other' },
  { name: 'MEASUREMENT-ALGINATE IMPRESSION', cost: 1000, category: 'Other' },
  { name: 'Tooth replantation', cost: 5000, category: 'Other' },
  { name: 'CHEQUE RETURN BANK FINE PAID CHARGE', cost: 200, category: 'Other' },
  { name: 'DUESTOM', cost: 118, category: 'Products' },
  { name: 'oden', cost: 750, category: 'Products' },
  { name: 'JC VITALIUM', cost: 900, category: 'Other' },
  { name: 'FPD', cost: 500, category: 'Other' },
  { name: 'JC -CERAMIC', cost: 2000, category: 'Other' },
  { name: 'medicines', cost: 0, category: 'Other' },
  { name: 'RPD-TOOTH ATTACHEMENT', cost: 0, category: 'Other' },
  { name: 'TOOTH ATTHACHMENT FOR RPD', cost: 500, category: 'Other' },
  { name: 'IMPLANT CROWN - CERAMIC CAT-CAM', cost: 5000, category: 'Implants' },
];
